name: Scan Repo

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  scan-repo:
    name: 🛡️ Scan Repo
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results to GitHub Security tab
      actions: read
      contents: read
    steps:
      - name: ⬇️ Check out code
        uses: actions/checkout@v5

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          cache: true
          version: v0.66.0

      - name: 🔬 Run Trivy vulnerability scanner in repo (SCA)
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          scanners: "vuln,config,secret"
          scan-type: "fs"
          scan-ref: "."
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-fs-results.sarif"
          input: "--skip-version-check"
          skip-setup-trivy: true

      - name: 📤 Upload Trivy filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-fs-results.sarif"
          category: trivy-filesystem
